// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuanzeznfeeevsyyayiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51YW56ZXpuZmVlZXZzeXlheWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjA3MTYsImV4cCI6MjA2OTE5NjcxNn0.EJfRwRxMyOmv1tYdd7PsKR3HJsLk1JCYBT8NkvtsOTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});